### ISSUE TITLE
Stef's code review

### ISSUE THREAD

**Issue by truenorth** [poteto/ember-cli-flash#44]
@stefanpenner Please review this before we start including it in a large number of Yahoo ember apps :)

**Comment by poteto** [comment]
@truenorth Cool, let me know how I can help! :)

**Comment by stefanpenner** [comment]
this project looks great, really nice!

This pass is mostly superficial, I will take some time tomorrow to use this in an app, and give better feedback.

I'm leaving some my comments in the form of todos, so that myself or someone else interested can make the appropriate updates :)

- [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/components/flash-message.js
   
    `run.scheduleOnce('afterRender', this, () => {` the onceness is detected based on the `this` and the function, but in this case the function is recreated on each call, so `once` can never happen

- [ ] many of the `computed` should actually be marked as readOnly
   
   - [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/components/flash-message.js#L39-L47
   - [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/components/flash-message.js#L32
   - [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/components/flash-message.js#L20
   - [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/components/flash-message.js#L18
   - [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/flash/object.js#L13-L20
   - [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/services/flash-messages-service.js#L21-L28

- [ ] missing `super`
   - [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/flash/object.js#L28

- [ ] state on prototype (these should likely be moved to init)
   - [ ] https://github.com/poteto/ember-cli-flash/blob/develop/addon/services/flash-messages-service.js#L18

- [ ] funky indentation: https://github.com/poteto/ember-cli-flash/blob/develop/addon/services/flash-messages-service.js#L77

- [ ] skipped tests https://github.com/poteto/ember-cli-flash/blob/develop/tests/acceptance/integration-test.js#L24-L45, likely missing `andThen`

**Comment by poteto** [comment]
Thanks for the review @stefanpenner!

**Comment by truenorth** [comment]
Thanks for making all of these improvements @poteto. We really appreciate it!

**Comment by stefanpenner** [comment]
:+1:
